const baum='https://www.gutenberg.org/files/55/55-h/55-h.htm';
const volkov='https://deti-online.com/skazki/volshebnik-izumrudnogo-goroda/';
const comparison='https://en.wikipedia.org/wiki/The_Wizard_of_the_Emerald_City';
const stops=[
{title:'It begins in Kansas',label:'Kansas',x:85,y:455,tag:'Different families',lead:'The same starting point. A different idea of home.',b:'Dorothy is an orphan who lives with Aunt Em and Uncle Henry.',v:'Ellie lives with her parents, John and Anna.',ru:'Дороти — сирота; Элли живёт с родителями.',word:'home · family · an orphan',meaning:'дом · семья · сирота',q:'How might a different family change the way we understand the journey?',ref:'Baum: Ch. I · Volkov: «Ураган»',src:volkov},
{title:'A storm, a spell, a voice',label:'The arrival',x:175,y:315,tag:'Cause & effect',lead:'How does the ordinary world become magical?',b:'A natural cyclone carries Dorothy to Oz. Toto does not speak in this book.',v:'Gingema creates the storm. In Magic Land, Totoshka can speak.',ru:'У Волкова ураган вызывает Гингема, а Тотошка начинает говорить.',word:'a cyclone · a spell · to speak',meaning:'циклон · заклинание · говорить',q:'What can a talking animal add to a story?',ref:'Baum: Ch. I–II · Volkov: arrival episodes',src:comparison},
{title:'Three wishes, three friends',label:'The companions',x:320,y:205,tag:'A shared pattern',lead:'Brains, a heart and courage: the travelling companions.',b:'The Scarecrow wants brains, the Tin Woodman a heart, and the Lion courage.',v:'The same wishes remain. Villina links Ellie’s return to helping three beings.',ru:'Желания друзей совпадают. Виллина связывает возвращение Элли с помощью троим.',word:'brains · a heart · courage',meaning:'мозги · сердце · смелость',q:'Do the friends already show the qualities they are looking for?',ref:'Baum: Ch. III–VI · Volkov: Villina’s advice',src:volkov},
{title:'An extra danger',label:'The ogre',x:460,y:345,tag:'Added by Volkov',lead:'One adaptation creates an adventure of its own.',b:'There is no matching ogre episode in Baum’s 1900 book.',v:'An ogre captures Ellie. Her friends rescue her.',ru:'Элли попадает к Людоеду; друзья её спасают. У Баума этого эпизода нет.',word:'an ogre · to capture · to rescue',meaning:'людоед · захватить · спасти',q:'How does an extra rescue scene develop the theme of friendship?',ref:'Baum: Ch. V–VI · Volkov: «Элли в плену у людоеда»',src:volkov},
{title:'Behind the green glasses',label:'Emerald City',x:620,y:260,tag:'Names & appearances',lead:'A new name. A familiar question about power.',b:'Oz rules the Emerald City. Visitors wear green spectacles.',v:'The ruler is called Goodwin (Гудвин). Green spectacles remain.',ru:'Оз становится Гудвином; зелёные очки сохраняются.',word:'a ruler · spectacles · appearances',meaning:'правитель · очки · внешние впечатления',q:'Why might an author keep the green spectacles in an adaptation?',ref:'Baum: Ch. X–XI · Volkov: Emerald City episodes',src:comparison},
{title:'The witch in the West',label:'The witch',x:700,y:100,tag:'A named antagonist',lead:'The next task takes the friends away from the city.',b:'Dorothy faces the Wicked Witch of the West. Water destroys the witch.',v:'Ellie faces Bastinda. Water destroys her too.',ru:'Злая ведьма Запада получает имя Бастинда; вода побеждает обеих.',word:'wicked · an enemy · to defeat',meaning:'злой · враг · победить',q:'What changes when an unnamed character receives a personal name?',ref:'Baum: Ch. XII · Volkov: Bastinda episodes',src:comparison},
{title:'The wizard is human',label:'The revelation',x:510,y:125,tag:'A shared discovery',lead:'Return to the city, and look beyond the performance.',b:'Oz is an ordinary man. He leaves in a balloon without Dorothy.',v:'Goodwin is also an ordinary man. Ellie misses his balloon departure.',ru:'Оба волшебника — обычные люди; обе девочки остаются после отлёта шара.',word:'a humbug · a balloon · to pretend',meaning:'обманщик · воздушный шар · притворяться',q:'Does the wizard’s secret make the friends’ achievements less real?',ref:'Baum: Ch. XV–XVII · Volkov: Goodwin’s secret',src:comparison},
{title:'The power to go home',label:'Home again',x:670,y:495,tag:'A shared ending',lead:'The last stop takes us back to the first question: home.',b:'Glinda explains the silver shoes’ power. Dorothy returns to Kansas.',v:'Stella explains the silver shoes’ power. Ellie returns home.',ru:'Глинда и Стелла объясняют силу серебряных башмачков. Героини возвращаются домой.',word:'silver · to return · to belong',meaning:'серебряный · вернуться · принадлежать',q:'What stays the same at the heart of these two stories?',ref:'Baum: Ch. XXIII–XXIV · Volkov: Stella and the ending',src:comparison}
];
const isRu=document.documentElement.lang==='ru';
const t=(en,ru)=>isRu?ru:en;
const russianStops=[
{title:'Всё начинается в Канзасе',label:'Канзас',tag:'Разные семьи',lead:'Одна отправная точка — разное представление о доме.',b:'Дороти — сирота. Она живёт с тётей Эм и дядей Генри.',v:'Элли живёт с родителями — Джоном и Анной.',q:'Как различия в семьях героинь могут повлиять на наше восприятие путешествия?',ref:'Баум: гл. I · Волков: «Ураган»'},
{title:'Ураган, заклинание и голос',label:'Прибытие',tag:'Причины событий',lead:'Как обычный мир становится волшебным?',b:'Природный циклон уносит Дороти в страну Оз. В этой книге Тото не разговаривает.',v:'Гингема вызывает ураган. В Волшебной стране Тотошка обретает дар речи.',q:'Что говорящий пёс добавляет к истории?',ref:'Баум: гл. I–II · Волков: прибытие в Волшебную страну'},
{title:'Три желания, три друга',label:'Попутчики',tag:'Общий мотив',lead:'Мозги, сердце и смелость: о чём мечтают спутники?',b:'Страшила хочет получить мозги, Железный Дровосек — сердце, а Лев — смелость.',v:'Желания друзей сохраняются. Виллина связывает возвращение Элли с помощью трём существам.',q:'Проявляют ли друзья уже в пути те качества, которые хотят получить?',ref:'Баум: гл. III–VI · Волков: совет Виллины'},
{title:'Ещё одна опасность',label:'Людоед',tag:'Добавлено Волковым',lead:'В адаптации появляется самостоятельное приключение.',b:'В книге Баума 1900 года нет соответствующего эпизода с Людоедом.',v:'Людоед захватывает Элли. Друзья её спасают.',q:'Как дополнительная сцена спасения раскрывает тему дружбы?',ref:'Баум: гл. V–VI · Волков: «Элли в плену у людоеда»'},
{title:'За зелёными очками',label:'Изумрудный город',tag:'Имена и видимость',lead:'Новое имя — знакомый вопрос о власти.',b:'Изумрудным городом правит Оз. Посетители носят зелёные очки.',v:'Правителя зовут Гудвин. Зелёные очки сохраняются.',q:'Почему автор мог сохранить зелёные очки в своей адаптации?',ref:'Баум: гл. X–XI · Волков: эпизоды в Изумрудном городе'},
{title:'Ведьма на западе',label:'Ведьма',tag:'Имя для злодейки',lead:'Новое задание уводит друзей из города.',b:'Дороти встречается со Злой Ведьмой Запада. Вода уничтожает ведьму.',v:'Элли встречается с Бастиндой. Её тоже уничтожает вода.',q:'Что меняется, когда безымянный персонаж получает собственное имя?',ref:'Баум: гл. XII · Волков: эпизоды с Бастиндой'},
{title:'Волшебник — человек',label:'Разоблачение',tag:'Общее открытие',lead:'Вернёмся в город и заглянем за кулисы.',b:'Оз оказывается обычным человеком. Он улетает на воздушном шаре без Дороти.',v:'Гудвин — тоже обычный человек. Элли остаётся после отлёта его шара.',q:'Обесценивает ли тайна волшебника настоящие достижения его друзей?',ref:'Баум: гл. XV–XVII · Волков: разоблачение Гудвина'},
{title:'Волшебство возвращения',label:'Снова дома',tag:'Общий финал',lead:'Последняя остановка возвращает нас к теме дома.',b:'Глинда объясняет силу серебряных башмачков. Дороти возвращается в Канзас.',v:'Стелла объясняет силу серебряных башмачков. Элли возвращается домой.',q:'Что остаётся неизменным в основе обеих историй?',ref:'Баум: гл. XXIII–XXIV · Волков: Стелла и заключение'}
];
if(isRu)stops.forEach((s,i)=>Object.assign(s,russianStops[i]));
const mapPositions=[[96,505],[722,314],[673,373],[638,455],[400,278],[145,212],[447,253],[388,518]];
const mapNamesEn=['Kansas','Munchkin village','The companions','The ogre','Emerald City','The witch’s castle','Back to the city','The way home'];
const mapNamesRu=['Канзас','Деревня Жевунов','Попутчики','Людоед','Изумрудный город','Замок ведьмы','Снова в городе','Дорога домой'];
stops.forEach((s,i)=>{[s.x,s.y]=mapPositions[i];s.label=t(mapNamesEn[i],mapNamesRu[i]);});
let current=0,zoom=1;const visited=new Set();
const pins=document.getElementById('pins');
pins.innerHTML=stops.map((s,i)=>`<button class="pin pin-${i+1}" style="left:${s.x/8}%;top:${s.y/6}%" data-index="${i}" aria-label="${t('Stop','Остановка')} ${i+1}: ${s.label}">${i+1}<span class="pin-label">${s.label}</span></button>`).join('');
function select(i){document.getElementById('otherLanguage').href=(isRu?'index.html':'ru.html')+'#stop-'+(i+1);current=i;visited.add(i);const s=stops[i];document.querySelectorAll('.pin').forEach((p,j)=>{p.classList.toggle('selected',j===i);p.classList.toggle('visited',visited.has(j));p.setAttribute('aria-pressed',String(j===i))});document.getElementById('progress').textContent=t(`${visited.size} / 8 explored`,`Пройдено: ${visited.size} / 8`);document.getElementById('story').innerHTML=`<div class="story-kicker">${t('STOP','ТОЧКА')} ${String(i+1).padStart(2,'0')} ${t('OF','ИЗ')} 08 <span class="tag">${s.tag}</span></div><h2>${s.title}</h2><p class="lead">${s.lead}</p><div class="book"><div class="book-label">${t('L. FRANK BAUM · 1900','Л. ФРЭНК БАУМ · 1900')}</div><p>${s.b}</p></div><div class="book volkov"><div class="book-label">${t('ALEXANDER VOLKOV · REVISED 1959','АЛЕКСАНДР ВОЛКОВ · РЕДАКЦИЯ 1959')}</div><p>${s.v}</p><p class="ru" lang="ru">${s.ru}</p></div><div class="word"><span>${t('WORDS FOR YOUR JOURNEY','СЛОВА ДЛЯ ПУТЕШЕСТВИЯ')}</span><span class="vocab-en" lang="en">${s.word}</span><span class="${isRu?'vocab-translation':'ru'}" lang="ru">${s.meaning}</span></div><p class="question"><b>${t('LET’S COMPARE','ДАВАЙ СРАВНИМ')}</b>${s.q}</p><p class="source-note">${s.ref}<br><a href="${baum}" target="_blank" rel="noopener">${t('Baum text','Текст Баума (EN)')}</a> · <a href="${s.src}" target="_blank" rel="noopener">${s.src===comparison?t('Comparison reference','Сравнение (EN)'):t('Volkov text & contents','Текст и оглавление Волкова')}</a></p><div class="story-controls"><button id="prev" ${i===0?'disabled':''}>${t('Previous','Назад')}</button><span class="position">${i+1} / 8</span><button class="next" id="next">${i===7?t('Start again','В начало'):t('Next stop','Далее')}</button></div>`;document.getElementById('prev').onclick=()=>select(current-1);document.getElementById('next').onclick=()=>select((current+1)%8);focusMapPoint(i)}
pins.addEventListener('click',e=>{const pin=e.target.closest('.pin');if(pin)select(Number(pin.dataset.index))});
if(document.getElementById('language'))document.getElementById('language').onclick=function(){const active=document.body.classList.toggle('show-ru');this.setAttribute('aria-pressed',String(active));this.querySelector('span').textContent=active?'ON':'OFF'};
function setZoom(z){zoom=Math.max(1,Math.min(1.8,z));document.getElementById('canvas').style.width=`${zoom*100}%`;document.getElementById('reset').textContent=`${Math.round(zoom*100)}%`;document.getElementById('zoomout').disabled=zoom===1;document.getElementById('zoomin').disabled=zoom===1.8;focusMapPoint(current);}
document.getElementById('zoomout').onclick=()=>setZoom(zoom-.2);document.getElementById('zoomin').onclick=()=>setZoom(zoom+.2);document.getElementById('reset').onclick=()=>{setZoom(1);document.getElementById('mapWindow').scrollTo(0,0)};
const dialog=document.getElementById('info');document.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
function info(html){document.getElementById('infoContent').innerHTML=html;dialog.showModal()}
document.getElementById('about').onclick=()=>info(`<div class="eyebrow">ABOUT THE PROJECT</div><h2>One route. Two literary worlds.</h2><p>This bilingual project for an English class compares <i>The Wonderful Wizard of Oz</i> by L. Frank Baum (1900) with <i>Волшебник Изумрудного города</i> by Alexander Volkov (first published in 1939; substantially revised in 1959).</p><p>The comparisons concern the familiar revised Volkov story, not every edition. English names such as Ellie and Goodwin are transliterations; English summaries on this site are original paraphrases, not quotations from a published translation.</p><h3>Research question</h3><p>How does adaptation change characters and events while preserving a recognisable journey?</p><h3>How to explore</h3><p>Select any numbered stop, or use “Next stop”. Zoom in to study the route; scroll the map to move around. Choose Русский for the full Russian version, or turn on RU notes for short Russian explanations and vocabulary meanings.</p><h3>For your presentation</h3><p>Choose two differences and one similarity. Explain each in English, then give your own interpretation of its effect. The discussion questions suggest possible interpretations; they do not claim to prove either author’s intentions.</p><p lang="ru">Это сравнение литературных произведений, а не экранизаций. Волков создал адаптацию, поэтому его книгу точнее называть переработкой, а не просто русским переводом Баума.</p>`);
document.getElementById('sources').onclick=()=>info(`<div class="eyebrow">READING & REFERENCES</div><h2>Go back to the books.</h2><ol><li><a href="${baum}" target="_blank" rel="noopener">L. Frank Baum — The Wonderful Wizard of Oz</a><br>Project Gutenberg. Full English text, 1900. Chapter references appear at every stop.</li><li><a href="${volkov}" target="_blank" rel="noopener">Александр Волков — Волшебник Изумрудного города</a><br>Russian reading text and chapter contents. Use the chapter titles to find the matching episode in your own edition.</li><li><a href="${comparison}" target="_blank" rel="noopener">The Wizard of the Emerald City — comparison and publication history</a><br>Secondary reference for the 1939/1959 distinction and changes between the books.</li></ol><p>The route is a selective reading guide. It combines comparable episodes and includes a stop unique to Volkov. It does not reproduce either book’s geographical map.</p><p><strong>A useful detail:</strong> the shoes are silver in both books. Do not confuse the books with film adaptations.</p>`);
if(isRu){
document.getElementById('about').onclick=()=>info(`<div class="eyebrow">О ПРОЕКТЕ</div><h2>Один путь. Два литературных мира.</h2><p>Этот двуязычный проект по английскому языку сравнивает <i>«Удивительного волшебника из страны Оз»</i> Лаймена Фрэнка Баума (1900) и <i>«Волшебника Изумрудного города»</i> Александра Волкова (первое издание — 1939; существенная переработка — 1959).</p><p>Сравнение относится к известной переработанной версии Волкова, а не ко всем изданиям. Английские имена Ellie и Goodwin передают русские имена. Тексты карточек — краткий пересказ, а не цитаты из опубликованного перевода.</p><h3>Исследовательский вопрос</h3><p>Как адаптация меняет героев и события, сохраняя узнаваемое путешествие?</p><h3>Как пользоваться картой</h3><p>Нажми на любую пронумерованную точку или кнопку «Далее». Увеличивай и прокручивай карту, чтобы изучить маршрут. Переключатель English / Русский меняет язык всего сайта. Английская лексика с переводом остаётся в русской версии для подготовки к уроку.</p><h3>Для защиты проекта</h3><p>Выбери два различия и одно сходство. Объясни их на английском и предложи собственную интерпретацию. Вопросы для обсуждения помогают размышлять, но не доказывают намерения авторов.</p><p>Здесь сравниваются книги, а не экранизации. Книгу Волкова точнее называть литературной адаптацией, а не просто русским переводом Баума.</p>`);
document.getElementById('sources').onclick=()=>info(`<div class="eyebrow">КНИГИ И СПРАВОЧНЫЕ МАТЕРИАЛЫ</div><h2>Обратимся к книгам.</h2><ol><li><a href="${baum}" target="_blank" rel="noopener">Л. Фрэнк Баум — The Wonderful Wizard of Oz</a><br>Project Gutenberg: полный английский текст книги 1900 года. В карточках указаны соответствующие главы.</li><li><a href="${volkov}" target="_blank" rel="noopener">Александр Волков — Волшебник Изумрудного города</a><br>Русский текст и оглавление. По названиям глав можно найти нужные эпизоды в своём издании.</li><li><a href="${comparison}" target="_blank" rel="noopener">Сравнение книг и история изданий (на английском)</a><br>Дополнительный источник о редакциях 1939 и 1959 годов и различиях между произведениями.</li></ol><p>На карте показаны избранные сопоставимые эпизоды и отдельное приключение, добавленное Волковым. Это схема чтения, а не географическая карта одной из книг.</p><p><strong>Полезная деталь:</strong> в обеих книгах башмачки серебряные. Не путай книги с экранизациями.</p>`);
}
const initialStop=Number(location.hash.match(/^#stop-([1-8])$/)?.[1]||1)-1;
function focusMapPoint(i){const map=document.getElementById('mapWindow'),canvas=document.getElementById('canvas');const x=stops[i].x/800*canvas.clientWidth,y=stops[i].y/600*canvas.clientHeight;map.scrollTo({left:Math.max(0,x-map.clientWidth/2),top:Math.max(0,y-map.clientHeight/2),behavior:'auto'});}
const mapWindow=document.getElementById('mapWindow');let dragState=null,dragged=false;
mapWindow.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button!==0||e.target.closest('button'))return;dragState={x:e.clientX,y:e.clientY,left:mapWindow.scrollLeft,top:mapWindow.scrollTop};dragged=false;mapWindow.setPointerCapture(e.pointerId);mapWindow.classList.add('dragging')});
mapWindow.addEventListener('pointermove',e=>{if(!dragState)return;const dx=e.clientX-dragState.x,dy=e.clientY-dragState.y;if(Math.abs(dx)+Math.abs(dy)>4)dragged=true;mapWindow.scrollLeft=dragState.left-dx;mapWindow.scrollTop=dragState.top-dy});
function endMapDrag(){dragState=null;mapWindow.classList.remove('dragging')}
mapWindow.addEventListener('pointerup',endMapDrag);mapWindow.addEventListener('pointercancel',endMapDrag);mapWindow.addEventListener('lostpointercapture',endMapDrag);
setZoom(1);select(initialStop);

